apiVersion: v1
kind: Service      #类型为k8s Service
metadata:
  name: mysql      #该Service的全局唯一名称
spec:
  ports:
   - port: 3306    #Service提供服务的端口号
  selector:        #Service对应的Pod拥有这里定义的标签
    app: mysql