apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-dm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: nginx-dm
    spec:
      containers:
      - name: nginx-dm
        image: nginx:1.9
        volumeMounts:
        - name: gluster-pv
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: gluster-pv
        persistentVolumeClaim:
          claimName: glusterfs-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dm
spec:
  selector:
    service: nginx-dm
  ports:
  - port: 80
    targetPort: 80